"""add cover_image to route

Revision ID: 1aeea7ae0411
Revises: b17a519fc19d
Create Date: 2026-04-10 19:20:11.339816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeea7ae0411'
down_revision = 'b17a519fc19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
