"""add waypoints to route

Revision ID: 27a9da997fc5
Revises: 9b68136acfbe
Create Date: 2026-04-15 19:03:34.697722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a9da997fc5'
down_revision = '9b68136acfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waypoints', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('waypoints')

    # ### end Alembic commands ###
