"""add chapters blocks topics

Revision ID: 43cc005b2217
Revises: b59a2516a1ee
Create Date: 2025-12-29 14:03:14.289197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cc005b2217'
down_revision = 'b59a2516a1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('default_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('location_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_asset_id', sa.String(length=26), nullable=True),
    sa.Column('caption_override', sa.String(length=255), nullable=True),
    sa.Column('link_label', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=1000), nullable=True),
    sa.Column('link_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['location_chapter.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('label_override', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['location_chapter.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'topic_id', name='uq_chapter_topic_once')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_topic')
    op.drop_table('chapter_block')
    op.drop_table('location_chapter')
    op.drop_table('topic')
    # ### end Alembic commands ###
