"""add supabase image tables

Revision ID: 83fd6fe3a2ff
Revises: 9520fa7f944c
Create Date: 2025-12-24 14:31:43.690241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fd6fe3a2ff'
down_revision = '9520fa7f944c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=26), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_images',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(length=26), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_images')
    op.drop_table('image_files')
    op.drop_table('images')
    # ### end Alembic commands ###
