"""add lat and lon to photo

Revision ID: 9520fa7f944c
Revises: bada3f7202ec
Create Date: 2025-11-23 19:40:03.043938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9520fa7f944c'
down_revision = 'bada3f7202ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('show_on_map', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('show_on_map')
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
