"""add route_type to route

Revision ID: 9b68136acfbe
Revises: 1aeea7ae0411
Create Date: 2026-04-15 18:50:50.305012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b68136acfbe'
down_revision = '1aeea7ae0411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_type', sa.String(length=20), server_default='walking', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('route_type')

    # ### end Alembic commands ###
