"""add location category

Revision ID: b17a519fc19d
Revises: 43cc005b2217
Create Date: 2025-12-29 17:47:22.368596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a519fc19d'
down_revision = '43cc005b2217'
branch_labels = None
depends_on = None


def upgrade():
    locationcategory = sa.Enum('LANDMARK', 'POI', 'PUB', 'COFFEE', name='locationcategory')
    locationcategory.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('LANDMARK', 'POI', 'PUB', 'COFFEE', name='locationcategory'), server_default='POI', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
